```{r Setup, include=FALSE}
rm(list=ls())

library(readxl)
library(xts)
library(readr)
library(doSNOW)
library(parallel)
library(neuralnet)
library(factoextra)

# Fix timestamps - this function creates an xts object from the piWebApiService function above
fix.timestamps <- function(pi.data) {
  ch.times <- pi.data[,2]
  ch.times <- sub("T", " ", ch.times)
  ch.times <- sub("Z", " ", ch.times)
  times <- as.POSIXct(ch.times)
  return(xts::xts(pi.data[,1], order.by = times))
}

# Install and load piwebapi package from Github
# install.packages("devtools")
# library(devtools)
# install_github("rbechalany/PI-Web-API-Client-R")
library(piwebapi)

# Login information
useKerberos <- TRUE
username <- "knewhart"
password <- "Lunabear2@"
validateSSL <- TRUE
debug <- TRUE
piWebApiService <- piwebapi$new("https://pivision/piwebapi", useKerberos, username, password, validateSSL, debug)
```



```{r Import data, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
pi.tags <- read_excel("pi-tags.xls")
pi.tags <- na.omit(pi.tags)
# Fix tags
for(i in 1:nrow(pi.tags)) {
  if(is.na(pi.tags[i,2])) next
  if(substr(pi.tags[i,2],1,12) == "\\\\APPLEPI_AF") pi.tags[i,2] <- paste0("af:", pi.tags[i,2])
  if(substr(pi.tags[i,2],1,9) == "\\\\applepi") pi.tags[i,2] <- paste0("pi:", pi.tags[i,2])
}


pi.tags.2.remove <- c("South Primary Influent Flow", "South Secondary Influent Flow")
pi.tags.2.remove <- sapply(pi.tags.2.remove, function(x) which(x == pi.tags[,1]))
pi.tags <- pi.tags[-pi.tags.2.remove,]

AB.Inf.Flow <- grep("Influent Flow", pi.tags$Name)
AB.RAS.Flow <- grep("RAS Flow", pi.tags$Name)
AB.RAS.TSS <- grep("RAS TSS", pi.tags$Name)
AB.A.DO <- grep("A DO", pi.tags$Name)
AB.B.DO <- grep("B DO", pi.tags$Name)
AB.C.DO <- grep("C DO", pi.tags$Name)
AB.A.Air <- grep("A Air", pi.tags$Name)
AB.B.Air <- grep("B Air", pi.tags$Name)
AB.C.Air <- grep("C Air", pi.tags$Name)
AB.A.NH3 <- grep("A NH3", pi.tags$Name)
AB.C.NH3 <- grep("C NH3", pi.tags$Name)
AB.A.NO3 <- grep("A NO3", pi.tags$Name)
AB.C.NO3 <- grep("C NO3", pi.tags$Name)
pi.tag.list <- c("AB.Inf.Flow", "AB.RAS.Flow", "AB.RAS.TSS", 
                 "AB.A.DO", "AB.B.DO", "AB.C.DO",
                 "AB.A.Air", "AB.B.Air", "AB.C.Air", 
                 "AB.A.NH3", "AB.C.NH3", "AB.A.NO3", "AB.C.NO3")

start <- paste0("2019-02-10", "T00:00:00Z")
end <- paste0("2019-04-16", "T00:00:00Z")
# end <- paste0(as.character(as.Date(Sys.time()) - 1), "T00:00:00Z")

# Load daily data
for(i in 1:nrow(pi.tags)) {
  # assign(make.names(pi.tags[i,1]), piWebApiService$data$getInterpolatedValues(path=unlist(pi.tags[i,2]), startTime = start, endTime = end, interval = "1d")[,1:2])
  # assign(make.names(pi.tags[i,1]), fix.timestamps(get(make.names(pi.tags[i,1]))))
  # new.objects <- c(new.objects, list(make.names(pi.tags[i,1])))
  
  data.holder <- piWebApiService$data$getInterpolatedValues(path=unlist(pi.tags[i,2]), startTime = start, endTime = end, interval = "1d")[,1:2]
  data.holder <- fix.timestamps(data.holder)
  colnames(data.holder) <- make.names(pi.tags[i,1])
  if (i == 1) {
    all.data <- data.holder
  } else {
    all.data <- cbind(all.data, data.holder)
  }
}

cols2keep <- which(!is.na(all.data[1,]))
all.data <- all.data[,cols2keep]

AB.Inf.Flow <- grep("Influent.Flow", colnames(all.data))
AB.RAS.Flow <- grep("RAS.Flow", colnames(all.data))
AB.RAS.TSS <- grep("RAS.TSS", colnames(all.data))
AB.A.DO <- grep("A.DO", colnames(all.data))
AB.B.DO <- grep("B.DO", colnames(all.data))
AB.C.DO <- grep("C.DO", colnames(all.data))
AB.A.Air <- grep("A.Air", colnames(all.data))
AB.B.Air <- grep("B.Air", colnames(all.data))
AB.C.Air <- grep("C.Air", colnames(all.data))
AB.A.NH3 <- grep("A.NH3", colnames(all.data))
AB.C.NH3 <- grep("C.NH3", colnames(all.data))
AB.A.NO3 <- grep("A.NO3", colnames(all.data))
AB.C.NO3 <- grep("C.NO3", colnames(all.data))
pi.tag.list <- c("AB.Inf.Flow", # All zeros
                 "AB.RAS.Flow", "AB.RAS.TSS", 
                 "AB.A.DO", "AB.B.DO", "AB.C.DO",
                 "AB.A.Air", "AB.B.Air", "AB.C.Air", 
                 "AB.A.NH3", "AB.C.NH3", "AB.A.NO3", "AB.C.NO3")
```


```{r PCA Cluster, echo=FALSE, message=FALSE, warning=FALSE}
pi.tag.data <- all.data[,c(unlist(sapply(pi.tag.list, function(x) get(x))))]
pi.tag.data <- pi.tag.data[,-grep("AB2.Influent.Flow", colnames(pi.tag.data))] # All zeros
pi.tag.data <- pi.tag.data[,-grep("AB2.RAS.Flow", colnames(pi.tag.data))] # All zeros
remove.rows <- unique(unlist(apply(pi.tag.data, 2, function(x) which(is.na(x)))))
pi.tag.data <- pi.tag.data[-remove.rows,]
pi.data.pca <- prcomp(pi.tag.data, center = TRUE,scale. = TRUE)
basins <- sapply(strsplit(colnames(pi.tag.data), "AB", "[.]"), "[", 2)
basins <- sapply(strsplit(basins, "[.]"), function(x) as.numeric(unlist(x)[1]))
devtools::install_github("vqv/ggbiplot")
library(ggbiplot)
ggbiplot(pi.data.pca, ellipse=TRUE)
```


```{r Distributions}
tiff(filename="MWRD_AB2_v1_density.tiff", units = "in", width = 20, height = 20, res = 200)
par(mfrow=c(round(sqrt(ncol(all.data)))+1, round(ncol(all.data)/round(sqrt(ncol(all.data))))),
    mar=c(3,3,3,1)+.01)
for(i in 1:ncol(all.data)) {
  plot(density(as.vector(na.omit(all.data[,i]))), 
       main = colnames(all.data)[i],
       xlab="", ylab="")
}
dev.off()

# tiff(filename="MWRD_AB2_v1_probability.tiff", units = "in", width = 20, height = 20, res = 200)
# par(mfrow=c(round(sqrt(ncol(all.data))), round(ncol(all.data)/round(sqrt(ncol(all.data))))),
    # mar=c(3,3,3,1)+.01)
for(i in 1:ncol(all.data)) {
  qqnorm(as.vector(na.omit(all.data[,i])), main = colnames(all.data)[i])
  qqline(as.vector(na.omit(all.data[,i])))
}
# dev.off()
```




```{r PCA}
pca.data <- scale(as.data.frame(na.omit(all.data)))
pca.results <- princomp(pca.data) # Spectral decomposition
tiff(filename="MWRD_AB2_v1_PCA.tiff", units = "in", width = 11, height = 6.5, res = 200)
fviz_pca_var(pca.results, labelsize = 3,
             col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,
             ggtheme=theme(axis.text=element_text(size=8), 
                           axis.title=element_text(size=8),
                           plot.title=element_text(size=8),
                           legend.title=element_text(size=8),
                           legend.text=element_text(size=8)
             ))
dev.off()

AB2 <- grep("AB2", colnames(all.data))
pca.data <- as.data.frame(na.omit(all.data[,AB2]))
pca.data <- pca.data[,-which(apply(pca.data,2,mean) == 0)]
pca.data <- scale(pca.data)
rownames(pca.data) <- seq(1:nrow(pca.data))
pca.results <- princomp(pca.data) # Spectral decomposition
tiff(filename="MWRD_AB2_v1_PCA_AB2.tiff", units = "in", width = 11, height = 6.5, res = 200)
fviz_pca_var(pca.results, labelsize = 3,
             col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,
             ggtheme=theme(axis.text=element_text(size=8), 
                           axis.title=element_text(size=8),
                           plot.title=element_text(size=8),
                           legend.title=element_text(size=8),
                           legend.text=element_text(size=8)
             ))
dev.off()

AB5 <- grep("AB5", colnames(all.data))
pca.data <- scale(as.data.frame(na.omit(all.data[,AB5])))
pca.results <- princomp(pca.data) # Spectral decomposition
tiff(filename="MWRD_AB2_v1_PCA_AB5.tiff", units = "in", width = 11, height = 6.5, res = 200)
fviz_pca_var(pca.results, labelsize = 3,
             col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,
             ggtheme=theme(axis.text=element_text(size=8), 
                           axis.title=element_text(size=8),
                           plot.title=element_text(size=8),
                           legend.title=element_text(size=8),
                           legend.text=element_text(size=8)
             ))
dev.off()

AB9 <- grep("AB9", colnames(all.data))
pca.data <- scale(as.data.frame(na.omit(all.data[,AB9])))
pca.results <- princomp(pca.data) # Spectral decomposition
tiff(filename="MWRD_AB2_v1_PCA_AB9.tiff", units = "in", width = 11, height = 6.5, res = 200)
fviz_pca_var(pca.results, labelsize = 3,
             col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,
             ggtheme=theme(axis.text=element_text(size=8), 
                           axis.title=element_text(size=8),
                           plot.title=element_text(size=8),
                           legend.title=element_text(size=8),
                           legend.text=element_text(size=8)
             ))
dev.off()

AB10 <- grep("AB10", colnames(all.data))
pca.data <- scale(as.data.frame(na.omit(all.data[,AB10])))
pca.results <- princomp(pca.data) # Spectral decomposition
tiff(filename="MWRD_AB2_v1_PCA_AB10.tiff", units = "in", width = 11, height = 6.5, res = 200)
fviz_pca_var(pca.results, labelsize = 3,
             col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,
             ggtheme=theme(axis.text=element_text(size=8), 
                           axis.title=element_text(size=8),
                           plot.title=element_text(size=8),
                           legend.title=element_text(size=8),
                           legend.text=element_text(size=8)
             ))
dev.off()

```



```{r PLS}
library(pls)
AB2 <- grep("AB2", colnames(all.data))
pls.data <- as.data.frame(na.omit(all.data[,AB2]))
pls.data <- pls.data[,-which(apply(pls.data,2,mean) == 0)]
pls.data <- as.data.frame(scale(pls.data))
rownames(pls.data) <- seq(1:nrow(pls.data))
pls.model <- plsr(North.AB2.C.NH3 ~ ., data = pls.data, validation = "CV")
# Find the number of dimensions with lowest cross validation error
cv = RMSEP(pls.model)
best.dims = which.min(cv$val[estimate = "adjCV", , ]) - 1
# Rerun the model
pls.model = plsr(North.AB2.C.NH3 ~ ., data = pls.data, ncomp = best.dims)

coefficients = coef(pls.model)
sum.coef = sum(sapply(coefficients, abs))
coefficients = coefficients * 100 / sum.coef
coefficients = sort(coefficients[, 1 , 1])
barplot(tail(coefficients, 5))
```

